Ajout du scrollView à la page DéfaultNotification
MCN-ING/Portefeuille-mobile-qc pull request #132
Opened 2024-09-23 17:35 UTC by ClaudeArs

2024-09-23 18:28 UTC, fc-santos commented on app/src/screens/DefaultNotification.tsx
> +          <Button
I faut ajouter un bouton secondaire pour revenir à la page d'accueil

2024-09-23 18:30 UTC, fc-santos requested changes
Voir mes commentaires ci-haut

2024-09-23 18:51 UTC, ClaudeArs commented on app/src/screens/DefaultNotification.tsx
> +          <Text style={styles.sectionDescriptionTitle}> {t('DefaultNotificationPage.Description')}</Text>
J'avais fait un test pour le scrollView, portant dans mon code je les ai enlevé

2024-09-24 15:01 UTC, fc-santos commented on app/src/screens/DefaultNotification.tsx
> +      height: '77%',
j'aurais peut-être mis flex: 3 pour ce container et dans le styles.button flex: 1. Comme ça container prend 3/4 et button 1/4.

2024-09-24 17:51 UTC, ClaudeArs commented on app/src/screens/DefaultNotification.tsx
> +      height: '77%',
![Capture d’écran, le 2024-09-24 à 13 34 38](https://github.com/user-attachments/assets/6e31e649-1035-40eb-9773-06895073aed6)

2024-09-24 18:25 UTC, fc-santos approved these changes

2024-09-24 18:25 UTC, merged