Adding History details
MCN-ING/Portefeuille-mobile-qc pull request #179
Opened 2024-12-13 02:19 UTC by ZouidiSamih

feat: Add detailed history tracking and UI updates

- Added new SVG icons for history events (Minus-Icon-Outline, changing-settings).
- Created `HistoryListItem.tsx` component for displaying detailed history items.
- Updated `ActivitiesStack.tsx` to include new history details navigation.
- Enhanced localization with new entries in `en/index.ts` and `fr/index.ts`.
- Updated `EventItem.tsx` and `NotificationListItem.tsx` for consistency.

https://github.com/user-attachments/assets/6a2f31a0-8dae-4ef2-b342-6419f14aef06

2024-12-13 12:26 UTC, fc-santos commented on app/package.json
> +    "@types/uuid": "^10.0.0",
Est-ce que cette dépendance est nécessaire ou c'était juste pendant que tu faisais un mock pour les données de l'historique ?

2024-12-13 12:42 UTC, fc-santos commented on app/src/components/HistoryListItem.tsx
> +  }
Je vois que le default c'est la fleur de lys, donc nous n'avons pas d'icônes pour les autres évènements (InformationNotSent, BiometricsChanged, WalletPINUpdated, etc) ?

2024-12-13 12:43 UTC, fc-santos commented on app/src/components/HistoryListItem.tsx
> +    const historyManager = agent ? loadHistory(agent) : undefined
Je pense que ne devrait pas créer un instance de historyManager à chaque fois qu'on supprime un élément de l'historique. Peut-être avoir un historyManager, setHistoryManager dans un useState?

2024-12-13 12:49 UTC, fc-santos commented on app/src/localization/en/index.ts
> +      BiometricUpdated: '{{operation}} of biometrics',
Pourquoi il y a le mot Authentication dans les évènements de CardXXX ? Est-ce qu'il te manque d'autres CardTitle ? Je vois qu'au moins InformationNotSent n'est pas là...

2024-12-13 12:50 UTC, fc-santos commented on app/src/localization/en/index.ts
> +      CardDeclined: 'Authentication Attestation {{cardName}} refused',
Encore, pourquoi le mot Authentication?

2024-12-13 12:52 UTC, fc-santos commented on app/src/localization/en/index.ts
> +      BiometricUpdated: 'Biometrics has been {{operation}}',
Encore ici, pourquoi le mot Authentication est là dans CardDeclined? Aussi, pas besoin ici des autres descriptions pour InformationSent, InformationNotSent ?

2024-12-13 12:53 UTC, fc-santos commented on app/src/localization/fr/index.ts
> +    HistoryDeleted_other: '{{ count }} historiques supprimés.',
Il faudrait s'assure qu'il y ait un moins une cohérence avec les noms. Ici, on parle d'historique mais plus bas à la ligne 1016, on parle d'évènement.

2024-12-13 12:55 UTC, fc-santos commented on app/src/navigators/ActivitiesStack.tsx
> +      <StackActivities.Screen name={BifoldScreens.ContactDetails} component={ContactDetails} />
Il te manque le title dans les options

2024-12-13 13:01 UTC, fc-santos commented on app/src/screens/activities/BiometricChangeDetails.tsx
> +const BiometricChangeDetails: React.FC = () => {
Puis ensuite ça devrait être ceci:

```typescript
const BiometricChangeDetails: React.FC<BiometricChangeDetailsProp> = ({ navigation, route }) => {
 // Refactor le reste du code ici
}
```

2024-12-13 13:02 UTC, fc-santos commented on app/src/screens/activities/BiometricChangeDetails.tsx
> +  }
Est-ce qu'il serait possible de sortir cette function dehors pour pouvoir la réutiliser dans les autres pages?

2024-12-13 13:04 UTC, fc-santos commented on app/src/screens/activities/CardChangedDetails.tsx
> +  }
Sortir cette function, voir mon commentaire dans BiometricChangeDetails screen.

2024-12-13 13:04 UTC, fc-santos commented on app/src/screens/activities/CardChangedDetails.tsx
> +          <Text style={styles.cardTitle}>{t('Attestation numérique d’identité gouvernementale')}</Text>
??

2024-12-13 13:06 UTC, fc-santos commented on app/src/screens/activities/HistoryDetail.tsx
> +type HistoryDetailRouteProp = RouteProp<ActivitiesStackParams, Screens.HistoryDetail>
Apporter les mêmes changements que j'ai mentionné dans BiometricChangeDetails.

2024-12-13 13:07 UTC, fc-santos commented on app/src/screens/activities/PinChangeDetails.tsx
> +  }
Encore, sortir cette fonction

2024-12-13 13:07 UTC, fc-santos commented on app/src/store.tsx
> +    historyTempDeletedIds: [],
Cela ne devrait plus exister, car la gestion se fait activities

2024-12-16 17:59 UTC, ZouidiSamih commented on app/package.json
> +    "@types/uuid": "^10.0.0",
La dépendance @types/uuid: "^10.0.0" est nécessaire pour assurer le typage correct de uuidv4() utilisé dans le keyExtractor. On utilise uuidv4() comme fallback pour générer des IDs uniques quand (item.content as HistoryRecord).id est manquant, afin d’éviter les conflits de clés dans la liste.

keyExtractor={(item: CustomRecord) => (item.content as HistoryRecord).id || uuidv4()}

2024-12-17 14:01 UTC, fc-santos commented on app/src/components/HistoryListItem.tsx
> +      //console.error('Failed to remove history item:', error)
Rajouter un toast de type erreur dans le bloc catch

2024-12-17 14:07 UTC, fc-santos commented on app/src/screens/activities/HistoryDetail.tsx
> +  const emailAddress = isHistoryRecordWithDetails(item.content) ? item.content.emailAddress : 'N/A'
C'est quoi ça ?

2024-12-17 14:08 UTC, fc-santos commented on app/src/screens/activities/HistoryDetail.tsx
> +  const correspondenceId = isHistoryRecordWithDetails(item.content) ? item.content.correspondenceId : 'N/A'
C'est quoi ça?

2024-12-17 14:10 UTC, fc-santos commented on app/src/screens/activities/HistoryDetail.tsx
> +              </Text>
Encore c'est quoi email address?

2024-12-17 14:12 UTC, jcdrouin21 commented on app/src/screens/activities/HistoryDetail.tsx
> +  const message = isHistoryRecordWithDetails(item.content) ? item.content.message : t('No message available')
Je ne pense pas que ce soit une clé de traduction valide."

2024-12-17 14:25 UTC, fc-santos reviewed
Voir mes nouveaux commentaires et fix les problèmes de build

2024-12-17 14:35 UTC, jcdrouin21 commented on app/src/screens/activities/HistoryList.tsx
> +        break
Lorsqu'on ne partage pas l'informations on va devoir apporter l'utilisateur vers une page qu'on a fait nous même (La navigation ici n'apporte pas à la bonne place). Il va falloir voir avec le UX la page doit ressemblé à quoi.

2024-12-17 14:51 UTC, jcdrouin21 commented on app/src/screens/activities/HistoryList.tsx
> +      // TODO Not tested
Il manque le cas d'utilisation ConnectionRemoved.
De plus, il va falloir valider que la connexion existe toujours avant de naviguer vers ContactDetails.

2025-01-10 15:51 UTC, fc-santos commented on app/ios/AriesBifold.xcodeproj/project.pbxproj
Le DEVELOPMENT_TEAM et le PRODUCT_BUNDLE_IDENTIFIER n'auraient pas du être changés

2025-01-10 15:52 UTC, fc-santos commented on app/src/localization/en/index.ts
> +    acceptedOn: 'Accepted on',
**A**cceptedOn

2025-01-10 15:54 UTC, fc-santos commented on app/src/localization/fr/index.ts
> +    acceptedOn: 'Accepté le',
**A**cceptedOn

2025-01-10 15:56 UTC, fc-santos commented on app/src/screens/activities/BiometricChangeDetails.tsx
> +      <TouchableOpacity
Ajouter un accessibilityLabel et accessibilityRole

2025-01-10 15:57 UTC, fc-santos commented on app/src/screens/activities/BiometricChangeDetails.tsx
> +        <HeaderText title={t('History.CardDescription.BiometricUpdated', { operation })} />
ajouter accessibilityRole={"header"}

2025-01-10 16:11 UTC, fc-santos commented on app/src/screens/activities/CardHistoryDetails.tsx
> +      <TouchableOpacity
Ajouter un accessibilityRole button

2025-01-10 16:12 UTC, fc-santos commented on app/src/screens/activities/ContactHistoryDetails.tsx
> +      <TouchableOpacity
Ajouter un accessibilityRole button

2025-01-10 16:17 UTC, fc-santos commented on app/src/screens/activities/PinChangeDetails.tsx
> +        <HeaderText title={t('History.CardDescription.WalletPinUpdated')} />
ajouter un accessibilityRole={"header"}

2025-01-10 16:18 UTC, fc-santos commented on app/src/screens/activities/PinChangeDetails.tsx
> +      <TouchableOpacity
ajouter un accessiblityRole={"button"}

2025-01-10 16:19 UTC, fc-santos commented on app/src/screens/activities/ProofHistoryDetails.tsx
> +        <HeaderText title={itemContent?.correspondenceName || ''} />
Ajouter accessibilityRole={"header"}

2025-01-10 16:20 UTC, fc-santos commented on app/src/screens/activities/ProofHistoryDetails.tsx
> +      <TouchableOpacity
Ajouter accessibilityRole={"button"}

2025-01-10 16:22 UTC, fc-santos requested changes
Il faudrait peut-être sortir les styles des écrans intermédiaires dans un hook du genre useHistoryDetailPageStyles. Je n'ai pas été capable de voir si les styles sont pareils dans BiometricChangeDetails, CardHistoryDetails, ContactHistoryDetails...

2025-01-13 16:18 UTC, jcdrouin21 commented on app/src/localization/fr/index.ts
> +      ContactUpdated: '{contactName} a été {{operation}}.',
{{contactName}}

2025-01-14 15:44 UTC, fc-santos commented on app/src/navigators/ActivitiesStack.tsx
> +import ProofDetails from '@hyperledger/aries-bifold-core/App/screens/ProofDetails'
Est-ce que c'est toujours nécessaire?

2025-01-14 15:47 UTC, fc-santos commented on app/src/screens/activities/CardHistoryDetails.tsx
> +        <Text style={styles.subTitle}>{itemContent?.correspondenceName}</Text>
utiliser la fonction startCase de lodash.starcase

2025-01-14 15:48 UTC, fc-santos reviewed
Voir commentaires

2025-01-20 19:18 UTC, fc-santos approved these changes

2025-01-21 14:10 UTC, merged